// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function All() {
  return window['go']['main']['App']['All']();
}

export function SendMsg(arg1, arg2) {
  return window['go']['main']['App']['SendMsg'](arg1, arg2);
}

export function ShowErrDialog(arg1) {
  return window['go']['main']['App']['ShowErrDialog'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
