// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function All():Promise<Array<string>>;

export function SendMsg(arg1:Array<string>,arg2:string):Promise<void>;

export function ShowErrDialog(arg1:string):Promise<void>;

export function Start(arg1:number):Promise<void>;

export function Status():Promise<boolean>;

export function Stop():Promise<void>;
